name: Deploy UPM Branch

on:
  push:
    brnaches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: upm
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: upm
        FOLDER: Assets/GameJamStarterKit
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
